"""
Django settings for dalgona project.
Generated by 'django-admin startproject' using Django 3.1.2.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import mimetypes
import datetime
from pathlib import Path
from .env_key import MY_SECRET_KEY, MY_DATABASES, MY_EMAIL_HOST_PASSWORD, MY_EMAIL_HOST_USER, IAMPORT_ACCESS_DATA


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = MY_SECRET_KEY


# ** 테스트시 주석 되어있는 거 풀어야함, 주석 안 되어있는 건 해야함 (시작)
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False


# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ["dalgonabackend.shop"]
# ** 테스트시 주석 되어있는 거 풀어야함, 주석 안 되어있는 건 해야함 (끝)


mimetypes.add_type("application/javascript", ".js", True)


# Application definition
INSTALLED_APPS = [
    # ** 테스트시 주석 해야함 (시작)
    'django_crontab',
    # ** 테스트시 주석 해야함 (끝)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'storages',

    # 앱
    'custom_admin',
    'accounts',
    'board_list',
    'image_manage',
    'board',
    # 투표게시판
    'battle',
    # news crawling
    'news',

    # 회원 관리
    'django.contrib.sites',
    'allauth',
    # 회원 삭제를 위해서 필요
    'allauth.socialaccount',
    'allauth.account',
    'rest_framework.authtoken',
    'rest_auth.registration',

    # cors 문제 해결
    'corsheaders',
    
    # 필터링
    'django_filters',

    # API 자동화
    'drf_yasg',

    'debug_toolbar',
]


# API 자동화
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'JWT_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    },
}


SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'dalgona.middleware.SameSiteMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]


AUTH_USER_MODEL = 'accounts.Profile'
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'


ROOT_URLCONF = 'dalgona.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'dalgona.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = MY_DATABASES 

# DRF Setting

# response 보낼 정보들이 적혀있는 Serializer
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.mypage_serializers.ProfileSerializer',
}

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.mypage_serializers.ProfileSerializer',
}


CRONTAB_COMMAND_SUFFIX = '2>&1'
CRONJOBS = [
    ('0 */3 * * *', 'news.crawling.save', '>> /var/log/cron.log'),
]


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

REST_USE_JWT = True
ACCOUNT_LOGOUT_ON_GET = True

JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_ALLOW_REFRESH': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=28),
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = MY_EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = MY_EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

URL_FRONT = 'https://wonderful-northcutt-c15dd2.netlify.app/'

ACCOUNT_CONFIRM_EMAIL_ON_GET = True

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_EMAIL_VERIFICATION = "none"

EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1

ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 5

ACCOUNT_EMAIL_SUBJECT_PREFIX = "✨별들의 리그 달고나"

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024000000 # value in bytes 1GB here
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024000000

CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "http://dalgonatest3.cafe24.com",
    "https://dalgonatest3.cafe24.com",
    "http://dalgona3.cafe24.com",
    "http://dalgona.me",
    "https://dalgona3.cafe24.com",
    "https://dalgona.me",
    "https://wonderful-northcutt-c15dd2.netlify.app",
    "http://wonderful-northcutt-c15dd2.netlify.app",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'

IAMPORT_ACCESS_DATA = IAMPORT_ACCESS_DATA
